name: finance_universe
description: "A comprehensive, multi-platform finance and investment tracker."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  glassmorphism: ^3.0.0 # FIX: Replaced glass_kit with the glassmorphism package

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # State Management
  flutter_riverpod: ^2.5.1

  # Utility
  intl: ^0.19.0
  uuid: ^4.4.0
  http: ^1.2.1

  # Google APIs & Auth
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0

  # File & Image Handling
  file_picker: ^8.0.5
  image_picker: ^1.1.2

  # Data Export & Security
  csv: ^6.0.0
  encrypt: ^5.0.3

  # ML / OCR
  google_mlkit_text_recognition: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/FinanceUniverse.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600