import 'package:hive/hive.dart';

part 'transaction.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
enum TransactionType {
  @HiveField(0)
  income,
  @HiveField(1)
  expense,
}

@HiveType(typeId: 1)
class Transaction extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late double amount;

  @HiveField(2)
  late String description;

  @HiveField(3)
  late String category;

  @HiveField(4)
  late DateTime date;

  @HiveField(5)
  late TransactionType type;

  @HiveField(6)
  late String paymentMethod;

  @HiveField(7)
  String? store;

  @HiveField(8)
  String? notes;

  @HiveField(9)
  bool isRecurring;

  Transaction({
    required this.id,
    required this.amount,
    required this.description,
    required this.category,
    required this.date,
    required this.type,
    required this.paymentMethod,
    this.store,
    this.notes,
    this.isRecurring = false,
  });
}