# Name of the workflow
name: Flutter CI

# This workflow runs on pushes to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Step 2: Sets up the Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use the major version of Flutter you are on
          channel: 'stable'
          cache: true # Caches dependencies for faster builds

      # Step 3: Gets Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run an analyzer to check for code quality issues
      - name: Analyze project
        run: flutter analyze

      # Step 5: Run tests (we'll add tests later, but this is good to have)
      - name: Run tests
        run: flutter test

      # Step 6: Build the Android App Bundle (for release)
      - name: Build Android App Bundle
        run: flutter build appbundle